"""create notification module tables

Revision ID: 1d96e40a400a
Revises: 6920460c59d7
Create Date: 2026-08-05 21:27:06.931052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d96e40a400a'
down_revision: Union[str, Sequence[str], None] = '6920460c59d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', name='deviceplatformenum'), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_devices_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token', name='uq_user_devices_device_token')
    )
    op.create_index('ix_user_devices_user_active', 'user_devices', ['user_id', 'is_active'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('appointment_confirmed', 'reminder_3_days', 'reminder_1_day', 'reminder_30_minutes', 'ready_for_consultation', 'consultation_delayed', 'appointment_cancelled', name='notificationtypeenum'), nullable=False),
    sa.Column('notification_status', sa.Enum('sent', 'failed', 'read', name='notificationstatusenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='fk_notification_logs_appointment_id'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='fk_notification_logs_patient_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_logs_appointment_id', 'notification_logs', ['appointment_id'], unique=False)
    op.create_index('ix_notification_logs_patient_id', 'notification_logs', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_logs_patient_id', table_name='notification_logs')
    op.drop_index('ix_notification_logs_appointment_id', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index('ix_user_devices_user_active', table_name='user_devices')
    op.drop_table('user_devices')
    # ### end Alembic commands ###
