"""create_medical_records_table

Revision ID: 2d565ec57c4a
Revises: 1d96e40a400a
Create Date: 2026-08-07 20:45:18.185467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d565ec57c4a'
down_revision: Union[str, Sequence[str], None] = '1d96e40a400a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('present_illness', sa.Text(), nullable=True),
    sa.Column('physical_examination', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='fk_medical_records_appointment_id'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name='fk_medical_records_doctor_id'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='fk_medical_records_patient_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', name='uq_medical_records_appointment_id')
    )
    op.create_index(
        "ix_medical_records_patient_id",
        "medical_records",
        ["patient_id"],
    )

    op.create_index(
        "ix_medical_records_doctor_id",
        "medical_records",
        ["doctor_id"],
    )

    op.create_index(
        "ix_medical_records_created_at",
        "medical_records",
        ["created_at"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_medical_records_created_at",
        table_name="medical_records",
    )

    op.drop_index(
        "ix_medical_records_doctor_id",
        table_name="medical_records",
    )

    op.drop_index(
        "ix_medical_records_patient_id",
        table_name="medical_records",
    )

    op.drop_table("medical_records")
    # ### end Alembic commands ###
