"""add checked_in to appointment status enum

Revision ID: 6920460c59d7
Revises: 42ef1dc57f72
Create Date: 2026-07-31 20:20:58.768923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6920460c59d7'
down_revision: Union[str, Sequence[str], None] = '42ef1dc57f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE appointmentstatusenum ADD VALUE IF NOT EXISTS 'checked_in';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
