"""create appointments table

Revision ID: 86738c3a47be
Revises: 929eefaa81be
Create Date: 2026-07-30 16:18:21.624671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86738c3a47be'
down_revision: Union[str, Sequence[str], None] = '929eefaa81be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', 'no_show', name='appointmentstatusenum'), nullable=False),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_appointments_department_id'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], name='fk_appointments_doctor_id'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='fk_appointments_patient_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'appointment_date', 'start_time', name='uq_appointments_doctor_date_start_time')
    )
    op.create_index(
    "ix_appointments_patient_id",
    "appointments",
    ["patient_id"],
    )

    op.create_index(
        "ix_appointments_doctor_id",
        "appointments",
        ["doctor_id"],
    )

    op.create_index(
        "ix_appointments_department_id",
        "appointments",
        ["department_id"],
    )

    op.create_index(
        "ix_appointments_appointment_date",
        "appointments",
        ["appointment_date"],
    )

    op.create_index(
        "ix_appointments_status",
        "appointments",
        ["status"],
    )
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_appointments_status")
    op.drop_index("ix_appointments_appointment_date")
    op.drop_index("ix_appointments_department_id")
    op.drop_index("ix_appointments_doctor_id")
    op.drop_index("ix_appointments_patient_id")

    op.drop_table("appointments")
    # ### end Alembic commands ###
